version: '2'
services:
  elasticsearch:
    image: elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
  ls01:
    image: logstash:7.5.2
    container_name: ls01
    ports:
      - "5044:5044"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /root/elk/ls01:/usr/share/logstash/pipeline/
    networks:
      - elk
    depends_on:
      - elasticsearch
  zoo01:
    image: zookeeper:3.5.6
    container_name: zoo01
    ports:
      - "2181:2181"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    networks:
      - elk
    depends_on:
      - elasticsearch
      - ls01
  kafka01:
    build: ./kafka01
    container_name: kafka01
    ports:
      - "9092:9092"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      KAFKA_BROKER_NAME: kafka01
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_PORT: 9092
      REPLICATION_FACTOR: 1
      ADVERTISED_LISTENER: PLAINTEXT://kafka01:9092
      ZOOKEEPER_NAME: zoo01
      KAFKA_ZOOKEEPER_CONNECT: "zoo01"
      KAFKA_CREATE_TOPICS: winlogbeat, filebeat
      KAFKA_HEAP_OPTS: -Xmx4G -Xms4G
      LOG_RETENTION_HOURS: 4
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEv                                                                                                                                                                                                                                             entHandler=INFO,state.change.logger=INFO"
    volumes:
      - /root/elk/kafka01/server.properties:/opt/elk/kafka/config/server.propert                                                                                                                                                                                                                                             ies
    networks:
      - elk
    depends_on:
      - elasticsearch
      - ls01
      - zoo01
  kibana:
    image: kibana:7.5.2
    container_name: kibana
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    depends_on:
      - elasticsearch
      - ls01
      - zoo01
      - kafka01
  nginx:
    build: /root/elk/nginx
    container_name: nginx 
    volumes:
      - /root/elk/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"    
    depends_on:
      - elasticsearch
      - ls01
      - zoo01
      - kafka01
      - kibana

volumes:
  data01:
    driver: local
  ls01pipeline:
    driver: local

networks:
  elk:
    driver: bridge
